// Auto-generated by `npm run sounds:sync` — do not edit by hand.
// To add a new sound, drop the .mp3 in the repo root and run the script.
// Loaded by index-v2.html and mixer.html so missing/renamed files surface
// in the console at boot instead of as a silent 404.
window.DESCENT_SOUNDS = Object.freeze([
  'abyss',
  'below-the-sea',
  'coral-reef',
  'dive-deep',
  'dolphin-song',
  'drone-filter',
  'factory-ambience',
  'humpback-whale',
  'industrial-spire',
  'machine-cycle',
  'metal-clanking',
  'metal-creak-long',
  'metal-creak-short',
  'pump-release',
  'spaceship-ambience',
  'trickling-loop',
  'underwater-ambience',
  'underwater-ambience-lake',
  'underwater-base',
  'underwater-choir',
  'valve-relief',
  'water-pipe',
  'whale-fx1',
  'whale-fx2',
  'whale-low',
  'whale-song',
]);
