#!/usr/bin/env node
// Auto-discovers .mp3 files in the repo root and rewrites sounds.js.
// Run after dropping new MP3s into the project, then commit sounds.js.
//
//   npm run sounds:sync

const fs = require('fs');
const path = require('path');

const repoRoot = path.resolve(__dirname, '..');
const mp3s = fs.readdirSync(repoRoot)
  .filter(f => f.endsWith('.mp3'))
  .map(f => f.replace(/\.mp3$/, ''))
  .sort();

const out = `// Auto-generated by \`npm run sounds:sync\` — do not edit by hand.
// To add a new sound, drop the .mp3 in the repo root and run the script.
// Loaded by index-v2.html and mixer.html so missing/renamed files surface
// in the console at boot instead of as a silent 404.
window.DESCENT_SOUNDS = Object.freeze([
${mp3s.map(n => `  '${n}',`).join('\n')}
]);
`;

const outPath = path.join(repoRoot, 'sounds.js');
fs.writeFileSync(outPath, out);
console.log(`Wrote ${outPath} with ${mp3s.length} sound${mp3s.length === 1 ? '' : 's'}:`);
mp3s.forEach(n => console.log(`  - ${n}`));
